export const availabilityOptionsTypes = {
  GET_AVAILABILITY_STATUSES_REQUEST: 'GET_AVAILABILITY_STATUSES_REQUEST',
  GET_AVAILABILITY_STATUSES_SUCCESS: 'GET_AVAILABILITY_STATUSES_SUCCESS',
  GET_AVAILABILITY_STATUSES_FAILURE: 'GET_AVAILABILITY_STATUSES_FAILURE',
  GET_AVAILABILITY_ITEMS_REQUEST: 'GET_AVAILABILITY_ITEMS_REQUEST',
  GET_AVAILABILITY_ITEMS_SUCCESS: 'GET_AVAILABILITY_ITEMS_SUCCESS',
  GET_AVAILABILITY_ITEMS_FAILURE: 'GET_AVAILABILITY_ITEMS_FAILURE',
  GET_AVAILABILITY_FOCUSES_REQUEST: 'GET_AVAILABILITY_FOCUSES_REQUEST',
  GET_AVAILABILITY_FOCUSES_SUCCESS: 'GET_AVAILABILITY_FOCUSES_SUCCESS',
  GET_AVAILABILITY_FOCUSES_FAILURE: 'GET_AVAILABILITY_FOCUSES_FAILURE'
};