export const musicGenresTypes = {
  GET_MUSIC_GENRES_REQUEST: 'GET_MUSIC_GENRES_REQUEST',
  GET_MUSIC_GENRES_SUCCESS: 'GET_MUSIC_GENRES_SUCCESS',
  GET_MUSIC_GENRES_FAILURE: 'GET_MUSIC_GENRES_FAILURE'
};