export const notificationsTypes = {
  GET_USER_NOTIFICATIONS_REQUEST: 'USER_NOTIFICATIONS_REQUEST',
  GET_USER_NOTIFICATIONS_SUCCESS: 'USER_NOTIFICATIONS_SUCCESS',
  GET_USER_NOTIFICATIONS_FAILURE: 'USER_NOTIFICATIONS_FAILURE',
};