export const profileTypes = {
  GET_PROFILE_INFO_REQUEST: 'PROFILE_INFO_REQUEST',
  GET_PROFILE_INFO_SUCCESS: 'PROFILE_INFO_SUCCESS',
  GET_PROFILE_INFO_FAILURE: 'PROFILE_INFO_FAILURE',
  GET_PROFILE_MAIN_PROJECTS_REQUEST: 'PROFILE_PROJECTS_REQUEST',
  GET_PROFILE_MAIN_PROJECTS_SUCCESS: 'PROFILE_PROJECTS_SUCCESS',
  GET_PROFILE_MAIN_PROJECTS_FAILURE: 'PROFILE_PROJECTS_FAILURE',
  GET_PROFILE_PORTFOLIO_PROJECTS_REQUEST: 'PROFILE_PROJECTS_REQUEST',
  GET_PROFILE_PORTFOLIO_PROJECTS_SUCCESS: 'PROFILE_PROJECTS_SUCCESS',
  GET_PROFILE_PORTFOLIO_PROJECTS_FAILURE: 'PROFILE_PROJECTS_FAILURE'
};