export const projectUsernameCheckTypes = {
  CHECK_PROJECTUSERNAME_REQUEST: 'CHECK_PROJECTUSERNAME_REQUEST',
  CHECK_PROJECTUSERNAME_SUCCESS: 'CHECK_PROJECTUSERNAME_SUCCESS',
  CHECK_PROJECTUSERNAME_FAILURE: 'CHECK_PROJECTUSERNAME_FAILURE'
};