export const projectTypes = {
  GET_PROJECT_INFO_REQUEST: 'PROJECT_INFO_REQUEST',
  GET_PROJECT_INFO_SUCCESS: 'PROJECT_INFO_SUCCESS',
  GET_PROJECT_INFO_FAILURE: 'PROJECT_INFO_FAILURE',
  GET_PROJECT_ADMINACCESS_REQUEST: 'PROFILE_ADMINACCESS_REQUEST',
  GET_PROJECT_ADMINACCESS_SUCCESS: 'PROFILE_ADMINACCESS_SUCCESS',
  GET_PROJECT_ADMINACCESS_FAILURE: 'PROFILE_ADMINACCESS_FAILURE',
  GET_PROJECT_MEMBERS_REQUEST: 'PROJECT_MEMBERS_REQUEST',
  GET_PROJECT_MEMBERS_SUCCESS: 'PROJECT_MEMBERS_SUCCESS',
  GET_PROJECT_MEMBERS_FAILURE: 'PROJECT_MEMBERS_FAILURE',
  GET_PROJECT_OPPORTUNITIES_REQUEST: 'PROJECT_OPPORTUNITIES_REQUEST',
  GET_PROJECT_OPPORTUNITIES_SUCCESS: 'PROJECT_OPPORTUNITIES_SUCCESS',
  GET_PROJECT_OPPORTUNITIES_FAILURE: 'PROJECT_OPPORTUNITIES_FAILURE',
  GET_PROJECT_NOTES_REQUEST: 'PROJECT_NOTES_REQUEST',
  GET_PROJECT_NOTES_SUCCESS: 'PROJECT_NOTES_SUCCESS',
  GET_PROJECT_NOTES_FAILURE: 'PROJECT_NOTES_FAILURE'
};