export const projectsTypes = {
  GET_USERS_MAIN_PROJECTS_REQUEST: 'USER_MAIN_PROJECTS_INFO_REQUEST',
  GET_USERS_MAIN_PROJECTS_SUCCESS: 'USER_MAIN_PROJECTS_INFO_SUCCESS',
  GET_USERS_MAIN_PROJECTS_FAILURE: 'USER_MAIN_PROJECTS_INFO_FAILURE',

  GET_USERS_PORTFOLIO_PROJECTS_REQUEST: 'USER_PORTFOLIO_PROJECTS_INFO_REQUEST',
  GET_USERS_PORTFOLIO_PROJECTS_SUCCESS: 'USER_PORTFOLIO_PROJECTS_INFO_SUCCESS',
  GET_USERS_PORTFOLIO_PROJECTS_FAILURE: 'USER_PORTFOLIO_PROJECTS_INFO_FAILURE',
};