export const searchTypes = {
  GET_SEARCH_RESULTS_REQUEST: 'GET_SEARCH_RESULTS_REQUEST',
  GET_SEARCH_RESULTS_SUCCESS: 'GET_SEARCH_RESULTS_SUCCESS',
  GET_SEARCH_RESULTS_FAILURE: 'GET_SEARCH_RESULTS_FAILURE',
};