export const searchTypes = {
  GET_SEARCH_RESULTS_REQUEST: 'GET_SEARCH_RESULTS_REQUEST',
  GET_SEARCH_RESULTS_SUCCESS: 'GET_SEARCH_RESULTS_SUCCESS',
  GET_SEARCH_RESULTS_FAILURE: 'GET_SEARCH_RESULTS_FAILURE',

  GET_SEARCHPROJECT_RESULTS_REQUEST: 'GET_SEARCHPROJECT_RESULTS_REQUEST',
  GET_SEARCHPROJECT_RESULTS_SUCCESS: 'GET_SEARCHPROJECT_RESULTS_SUCCESS',
  GET_SEARCHPROJECT_RESULTS_FAILURE: 'GET_SEARCHPROJECT_RESULTS_FAILURE',

  SEARCH_USERS_REQUEST: 'SEARCH_USERS_REQUEST',
  SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
  SEARCH_USERS_FAILURE: 'SEARCH_USERS_FAILURE',

  SEARCH_PROJECTS_REQUEST: 'SEARCH_PROJECTS_REQUEST',
  SEARCH_PROJECTS_SUCCESS: 'SEARCH_PROJECTS_SUCCESS',
  SEARCH_PROJECTS_FAILURE: 'SEARCH_PROJECTS_FAILURE',

  GET_SUGGESTEDUSERS_REQUEST: 'GET_SUGGESTEDUSERS_REQUEST',
  GET_SUGGESTEDUSERS_SUCCESS: 'GET_SUGGESTEDUSERS_SUCCESS',
  GET_SUGGESTEDUSERS_FAILURE: 'GET_SUGGESTEDUSERS_FAILURE'
};