export const userProjectsTypes = {
    GET_USER_PROJECTS_REQUEST: 'GET_USER_PROJECTS_REQUEST',
    GET_USER_PROJECTS_SUCCESS: 'GET_USER_PROJECTS_SUCCESS',
    GET_USER_PROJECTS_FAILURE: 'GET_USER_PROJECTS_FAILURE',
  };