export const userTypes = {
  GET_USER_INFO_REQUEST: 'USER_GETALL_REQUEST',
  GET_USER_INFO_SUCCESS: 'USER_GETALL_SUCCESS',
  GET_USER_INFO_FAILURE: 'USER_GETALL_FAILURE',

  GET_USERID_INFO_REQUEST: 'USERID_GETALL_REQUEST',
  GET_USERID_INFO_SUCCESS: 'USERID_GETALL_SUCCESS',
  GET_USERID_INFO_FAILURE: 'USERID_GETALL_FAILURE',

  GET_USER_GENRES_INFO_REQUEST: 'GET_USER_GENRES_INFO_REQUEST',
  GET_USER_GENRES_INFO_SUCCESS: 'GET_USER_GENRES_INFO_SUCCESS',
  GET_USER_GENRES_INFO_FAILURE: 'GET_USER_GENRES_INFO_FAILURE',

  GET_USER_ROLES_INFO_REQUEST: 'GET_USER_ROLES_INFO_REQUEST',
  GET_USER_ROLES_INFO_SUCCESS: 'GET_USER_ROLES_INFO_SUCCESS',
  GET_USER_ROLES_INFO_FAILURE: 'GET_USER_ROLES_INFO_FAILURE',

  GET_USER_GEAR_REQUEST: 'GET_USER_GEAR_REQUEST',
  GET_USER_GEAR_SUCCESS: 'GET_USER_GEAR_SUCCESS',
  GET_USER_GEAR_FAILURE: 'GET_USER_GEAR_FAILURE',

  GET_USER_AVAILABILITY_ITEMS_REQUEST: 'GET_USER_AVAILABILITY_ITEMS_REQUEST',
  GET_USER_AVAILABILITY_ITEMS_SUCCESS: 'GET_USER_AVAILABILITY_ITEMS_SUCCESS',
  GET_USER_AVAILABILITY_ITEMS_FAILURE: 'GET_USER_AVAILABILITY_ITEMS_FAILURE',

  GET_USER_LAST_CONNECTED_FRIENDS_REQUEST: 'GET_USER_LAST_CONNECTED_FRIENDS_REQUEST',
  GET_USER_LAST_CONNECTED_FRIENDS_SUCCESS: 'GET_USER_LAST_CONNECTED_FRIENDS_SUCCESS',
  GET_USER_LAST_CONNECTED_FRIENDS_FAILURE: 'GET_USER_LAST_CONNECTED_FRIENDS_FAILURE',
};